### ISSUE TITLE
Doesn't use a window function

### ISSUE THREAD

**Issue by hexafluoride** [le1ca/spectrogram#1]
http://www.katjaas.nl/FFTwindow/FFTwindow.html
This article explains why it's important to use a window function when performing a FFT(and goes way over my head while doing it).

**Comment by tmick0** [comment]
I implemented a Hann window with 4x overlap and it looks like it did a pretty good job at reducing spectral leakage:

![Comparison of unwindowed vs windowed DFT](http://i.imgur.com/KeXFK57.png)

The left is the original unwindowed result, the right is windowed.
